import { ArrowLeft, ArrowRight, ExternalLink } from 'lucide-react'
import Link from 'next/link'
import SiteHeader from '../../../components/SiteHeader'
import SiteFooter from '../../../components/SiteFooter'

const liveUrl = 'https://northstead-commercial-risk-l4776yxlv.vercel.app'

export default function NorthsteadCaseStudy() {
  return <main className="min-h-screen bg-[#090a0b] text-[#f4f4f3]">
    <SiteHeader />
    <section className="border-b border-white/[0.055] py-10 sm:py-16"><div className="mx-auto w-[min(1160px,calc(100%-28px))]"><Link href="/work" className="inline-flex items-center gap-2 text-[11px] font-semibold text-[#85868c] hover:text-white"><ArrowLeft className="h-3.5 w-3.5"/>Selected work</Link><p className="mt-10 text-[10px] font-extrabold uppercase tracking-[0.25em] text-[#d8cbb7]">Northstead Commercial Risk / Independent Concept</p><h1 className="mt-5 max-w-[950px] text-[clamp(42px,8vw,72px)] font-semibold leading-[0.98] tracking-[-0.055em]">Turning commercial risk into a clearer buying conversation.</h1><p className="mt-6 max-w-[700px] text-[16px] leading-7 text-[#96979c]">A concept exploring how a commercial insurance proposition can establish relevance, confidence and a clear next step without overwhelming the buyer.</p><a href={liveUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-[48px] items-center rounded-lg bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">View live concept<ExternalLink className="ml-2 h-4 w-4"/></a></div></section>

    <section className="border-b border-white/[0.055] py-10 sm:py-14"><div className="mx-auto w-[min(1160px,calc(100%-28px))]"><a href={liveUrl} target="_blank" rel="noreferrer" className="block overflow-hidden rounded-[20px] border border-white/[0.08] bg-[#111315] p-3 sm:p-5"><div className="overflow-hidden rounded-[13px] border border-white/[0.08]"><div className="flex h-10 items-center gap-1.5 bg-[#dedad2] px-4"><span className="h-2.5 w-2.5 rounded-full bg-black/15"/><span className="h-2.5 w-2.5 rounded-full bg-black/15"/><span className="h-2.5 w-2.5 rounded-full bg-black/15"/><span className="ml-4 text-[8px] font-bold uppercase tracking-[0.2em] text-black/35">northstead-commercial-risk / concept</span></div><div className="grid min-h-[430px] content-between bg-[#17201d] p-7 sm:p-12 lg:p-16"><div><p className="text-[9px] font-bold uppercase tracking-[0.24em] text-white/45">Commercial Insurance / Established Business</p><h2 className="mt-6 max-w-[780px] text-[clamp(38px,7vw,78px)] font-semibold leading-[0.95] tracking-[-0.055em] text-white">Commercial insurance built around your business.</h2><p className="mt-5 max-w-[520px] text-[14px] leading-7 text-white/55">Clarity first. A measured, high-trust direction designed to make a complex professional service easier to understand.</p></div><p className="mt-12 text-[10px] font-bold uppercase tracking-[0.2em] text-white/65">View the live prototype ↗</p></div></div></a></div></section>

    <section className="border-b border-white/[0.055] bg-[#0b0d0e] py-12 sm:py-16"><div className="mx-auto grid w-[min(1160px,calc(100%-28px))] gap-9 lg:grid-cols-2 lg:gap-16"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#d8cbb7]">The challenge</p><h2 className="mt-4 text-[clamp(30px,6vw,46px)] font-semibold leading-[1.03] tracking-[-0.045em]">Complex services can make the buyer work too hard.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">Commercial insurance naturally contains detail, terminology and multiple areas of cover. The concept tests a simpler route: establish who the proposition is for, communicate confidence, then move the buyer toward a useful conversation.</p></div><div><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#d8cbb7]">The direction</p><h2 className="mt-4 text-[clamp(30px,6vw,46px)] font-semibold leading-[1.03] tracking-[-0.045em]">Position expertise before products.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">The visual system stays restrained and the hierarchy does more of the work. Rather than treating every service as equally urgent, the page creates a deliberate sequence from relevance to confidence to action.</p></div></div></section>

    <section className="py-12 sm:py-16"><div className="mx-auto w-[min(1160px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#d8cbb7]">What the concept demonstrates</p><div className="mt-6 grid gap-3 md:grid-cols-3">{[['01','Explain','Establish the audience and proposition before asking the visitor to decode the service.'],['02','Prove','Use structure, restraint and professional hierarchy to support confidence without invented social proof.'],['03','Direct','Keep the route toward a conversation obvious rather than competing with multiple equal calls to action.']].map(([number,title,copy])=><article key={number} className="rounded-[17px] border border-white/[0.07] bg-[#0d0f10] p-5 sm:p-6"><p className="text-[9px] font-bold tracking-[0.18em] text-[#66676d]">{number}</p><h3 className="mt-5 text-[22px] font-semibold tracking-[-0.035em]">{title}</h3><p className="mt-3 text-[13px] leading-6 text-[#818288]">{copy}</p></article>)}</div><p className="mt-6 max-w-[800px] text-[11px] leading-6 text-[#66676d]">This is independent concept work created by Booth Marketing to demonstrate our approach to website strategy, design and conversion. Northstead Commercial Risk is not presented as a commissioned client project and no performance claims are implied.</p></div></section>

    <section className="border-t border-white/[0.055] bg-[#0b0d0e] py-12 text-center sm:py-16"><div className="mx-auto w-[min(760px,calc(100%-28px))]"><h2 className="text-[clamp(32px,7vw,48px)] font-semibold leading-[1.03] tracking-[-0.05em]">What would we change about your website?</h2><p className="mx-auto mt-4 max-w-[600px] text-[14px] leading-7 text-[#8c8d92]">Start with the current site. We will identify what deserves to stay, what is making the decision harder and what should change first.</p><Link href="/website-audit" className="mt-7 inline-flex min-h-[50px] items-center rounded-lg bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">Request Website Audit<ArrowRight className="ml-2.5 h-4 w-4"/></Link></div></section>
    <SiteFooter />
  </main>
}
