import { ArrowRight, Check, ChevronRight } from 'lucide-react'
import Link from 'next/link'
import SiteFooter from '../../components/SiteFooter'
import SiteHeader from '../../components/SiteHeader'

export default function AutomationPage() {
  return (
    <main className="min-h-screen bg-[#090a0b] text-[#f4f4f3]">
      <SiteHeader />
      <section className="border-b border-white/[0.055] py-12 sm:py-16"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.24em] text-[#d8cbb7]">Automation</p><h1 className="mt-4 max-w-[820px] text-[clamp(40px,9vw,62px)] font-semibold leading-[1.01] tracking-[-0.055em]">Once the customer arrives, the operation still has to handle what happens next.</h1><p className="mt-5 max-w-[730px] text-[15px] leading-7 text-[#929399]">Booth Marketing designs AI automation and workflow systems that reduce repetitive handling around the decisions your team still needs to make.</p></div></section>
      <section className="border-b border-white/[0.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><h2 className="max-w-[760px] text-[clamp(32px,7vw,48px)] font-semibold leading-[1.05] tracking-[-0.045em]">Your business can be bespoke without every step needing to stay manual.</h2><div className="mt-7 grid gap-3 lg:grid-cols-3">{[['System-led','Predictable, repeatable handling','Moving information, routine reminders, recurring documents and status updates.'],['Human approval','The system prepares. A person decides.','Approvals, recommendations, exceptions and sensitive actions where review still matters.'],['Human-led','Judgment stays human','Negotiation, commercial decisions, unusual situations and relationship-heavy work.']].map(([label,title,copy],index)=><div key={label} className={`rounded-[17px] border p-5 ${index===1?'border-[#d92f3c]/18 bg-[#190f11]/42':'border-white/[0.07] bg-[#0d0f10]'}`}><p className="text-[9.5px] font-extrabold uppercase tracking-[0.2em] text-[#cfc2ae]">{label}</p><h3 className="mt-3 text-[18px] font-semibold text-[#e2e2e4]">{title}</h3><p className="mt-2 text-[13px] leading-6 text-[#808187]">{copy}</p></div>)}</div><p className="mt-5 rounded-[15px] border border-white/[0.07] bg-[#0d0f10] p-5 text-[14px] font-semibold leading-6 text-[#dddde0]">Do not automate the judgment. Remove unnecessary handling around it.</p></div></section>
      <section className="border-b border-white/[0.055] py-10 sm:py-14"><div className="mx-auto grid w-[min(1080px,calc(100%-28px))] gap-5 lg:grid-cols-2"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#cfc2ae]">Keep what works</p><h2 className="mt-4 text-[clamp(30px,7vw,44px)] font-semibold tracking-[-0.045em]">Automation should reduce actions from the employee day, not create another system to babysit.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">We start with the workflow and the systems already in place before recommending anything new.</p></div><div className="rounded-[17px] border border-[#d92f3c]/18 bg-[#190f11]/42 p-5"><div className="space-y-3">{['Keep useful existing systems','Reduce copying and chasing','Preserve human control over important decisions','Avoid unnecessary dashboards','Start with one workflow, not a transformation programme'].map(item=><div key={item} className="flex items-start gap-2.5 text-[13px] leading-6 text-[#a49598]"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[#d8cbb7]" />{item}</div>)}</div></div></div></section>
      <section className="border-b border-white/[0.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#cfc2ae]">Example workflow</p><div className="mt-4 flex flex-wrap items-center gap-2">{['Enquiry','Qualification','Assignment','Follow-up','Reporting'].map((step,index,all)=><div key={step} className="flex items-center gap-2"><span className="rounded-lg border border-white/[0.075] bg-[#090a0b] px-3 py-2 text-[11px] text-[#aaaab0]">{step}</span>{index<all.length-1&&<ChevronRight className="h-3.5 w-3.5 text-[#66676d]" />}</div>)}</div><p className="mt-5 text-[13px] leading-6 text-[#85868c]">The goal is not to replace people. It is to stop people spending time on work a system can reliably handle.</p></div></section>
      <section className="py-12 text-center sm:py-16"><div className="mx-auto w-[min(760px,calc(100%-28px))]"><h2 className="text-[clamp(34px,7.5vw,50px)] font-semibold leading-[1.04] tracking-[-0.048em]">Start with one process that feels harder to run than it should.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">Leave knowing what is worth automating, what is not, and where to start.</p><Link href="/automation-audit" className="mt-6 inline-flex min-h-[50px] items-center justify-center rounded-lg border border-[#efe3cf] bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">Request an Automation Audit<ArrowRight className="ml-2.5 h-4 w-4" /></Link></div></section>
      <SiteFooter />
    </main>
  )
}
