import { ArrowRight, Check } from 'lucide-react'
import Link from 'next/link'
import SiteHeader from '../../components/SiteHeader'
import SiteFooter from '../../components/SiteFooter'

export default function AutomationPage(){return <main className="min-h-screen bg-[#090a0b] text-[#f4f4f3]"><SiteHeader/>
<section className="border-b border-white/[0.055] py-14 sm:py-20"><div className="mx-auto w-[min(960px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.24em] text-[#d8cbb7]">Practical Business Automation</p><h1 className="mt-4 max-w-[850px] text-[clamp(42px,9vw,68px)] font-semibold leading-[1] tracking-[-0.055em]">Improve what happens after the customer acts.</h1><p className="mt-6 max-w-[720px] text-[15px] leading-7 text-[#929399]">Booth Marketing's primary work is conversion-focused websites and landing pages. Where the operational work around an enquiry creates avoidable friction, we can also design practical automation around the real workflow.</p><Link href="/automation-audit" className="mt-7 inline-flex min-h-[50px] items-center rounded-lg bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">Request Automation Audit<ArrowRight className="ml-2 h-4 w-4"/></Link></div></section>
<section className="border-b border-white/[0.055] py-12"><div className="mx-auto w-[min(960px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#d8cbb7]">Where it fits</p><h2 className="mt-4 max-w-[720px] text-[clamp(30px,6vw,46px)] font-semibold tracking-[-0.045em]">Discovery → Decision → Conversion → Operation</h2><p className="mt-4 max-w-[720px] text-[14px] leading-7 text-[#8d8e94]">The website helps turn consideration into trust and action. Automation can then reduce unnecessary manual work around the processes that support that action.</p><div className="mt-8 grid gap-3 md:grid-cols-2">{[['Enquiry handling','Move useful enquiry information to the right place without repetitive copying.'],['Follow-up','Support consistent follow-up where a defined process already exists.'],['Onboarding','Reduce repetitive handoffs and administration after a customer decides to proceed.'],['Data movement','Connect clearly defined systems where people are manually moving the same information.']].map(([t,c])=><div key={t} className="rounded-[16px] border border-white/[0.07] bg-[#0d0f10] p-5"><Check className="h-4 w-4 text-[#d8cbb7]"/><h3 className="mt-3 font-semibold">{t}</h3><p className="mt-2 text-[13px] leading-6 text-[#85868c]">{c}</p></div>)}</div></div></section>
<section className="py-14 text-center"><div className="mx-auto w-[min(720px,calc(100%-28px))]"><h2 className="text-[clamp(30px,6vw,46px)] font-semibold tracking-[-0.045em]">Automate the friction, not the business.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">We start with the workflow before deciding whether automation is justified. Sometimes the right answer is to simplify, improve or leave a process alone.</p><Link href="/automation-audit" className="mt-6 inline-flex min-h-[50px] items-center rounded-lg border border-[#efe3cf] bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">Request Automation Audit<ArrowRight className="ml-2 h-4 w-4"/></Link></div></section><SiteFooter/></main>}
