import { ArrowRight, Check } from 'lucide-react'
import Link from 'next/link'
import SiteFooter from '../../components/SiteFooter'
import SiteHeader from '../../components/SiteHeader'

const deliverables = [
  ['Strategy & page architecture', 'Clarify the buyer journey, page roles and what each page needs to achieve.'],
  ['Messaging & offer structure', 'Turn vague positioning into clear, decision-useful communication.'],
  ['Responsive design', 'Design the experience around mobile and tablet as seriously as desktop.'],
  ['Development', 'Build a fast, maintainable site around the agreed structure and content.'],
  ['Service & landing pages', 'Create focused paths for offers, campaigns and audiences where the business needs them.'],
  ['Launch foundations', 'Performance, search clarity, forms, metadata and launch QA appropriate to the agreed scope.'],
]

export default function WebsitesPage() {
  return (
    <main className="min-h-screen bg-[#090a0b] text-[#f4f4f3]">
      <SiteHeader />
      <section className="border-b border-white/[0.055] py-12 sm:py-16"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.24em] text-[#d8cbb7]">Conversion-Focused Websites</p><h1 className="mt-4 max-w-[820px] text-[clamp(40px,9vw,62px)] font-semibold leading-[1.01] tracking-[-0.055em]">Built for the decision that happens after discovery.</h1><p className="mt-5 max-w-[730px] text-[15px] leading-7 text-[#929399]">AI-assisted search is shortening parts of the research journey. Your website still carries the trust, positioning and conversion work once a serious buyer arrives.</p><p className="mt-3 max-w-[720px] text-[13px] leading-6 text-[#77787e]">We think of the website as conversion infrastructure: the system between attention and action.</p></div></section>

      <section className="border-b border-white/[0.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><h2 className="max-w-[760px] text-[clamp(32px,7vw,48px)] font-semibold leading-[1.05] tracking-[-0.045em]">What we actually build around</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Offer clarity','The buyer should understand what you do without decoding vague marketing language.'],['Positioning','The site should make a clear case for why your business deserves consideration.'],['Proof','Credibility should appear where doubt appears, not buried on a generic testimonials page.'],['Mobile-first UX','High-intent traffic should get a purpose-built mobile journey, not a shrunken desktop one.'],['Landing pages','Specific offers, campaigns and audiences need specific conversion paths.'],['Answer-engine clarity','Services, expertise, proof and intent should be easy for both people and AI systems to interpret.']].map(([title,copy])=><div key={title} className="rounded-[16px] border border-white/[0.07] bg-[#0d0f10] p-5"><p className="text-[15px] font-semibold text-[#e2e2e4]">{title}</p><p className="mt-2 text-[13px] leading-6 text-[#808187]">{copy}</p></div>)}</div></div></section>

      <section className="border-b border-white/[0.055] py-10 sm:py-14"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#d8cbb7]">What an engagement can include</p><h2 className="mt-4 max-w-[760px] text-[clamp(31px,7vw,46px)] font-semibold leading-[1.05] tracking-[-0.045em]">The work is scoped around the business problem, not a fixed website package.</h2><p className="mt-4 max-w-[730px] text-[14px] leading-7 text-[#8d8e94]">After diagnosis, we agree what is genuinely required. A focused landing-page build should not be sold like a full website transformation.</p><div className="mt-7 grid gap-3 md:grid-cols-2">{deliverables.map(([title,copy],index)=><div key={title} className="grid grid-cols-[34px_1fr] gap-3 rounded-[16px] border border-white/[0.07] bg-[#0d0f10] p-4 sm:p-5"><span className="pt-1 text-[9px] font-bold tracking-[0.16em] text-[#77787e]">0{index+1}</span><div><p className="text-[14px] font-semibold text-[#e2e2e4]">{title}</p><p className="mt-1.5 text-[12px] leading-6 text-[#808187]">{copy}</p></div></div>)}</div></div></section>

      <section className="border-b border-white/[0.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto grid w-[min(1080px,calc(100%-28px))] gap-5 lg:grid-cols-2"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#cfc2ae]">Different intent needs different pages</p><h2 className="mt-4 text-[clamp(30px,7vw,44px)] font-semibold tracking-[-0.045em]">One homepage is rarely enough.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">A referral visitor, paid campaign visitor and AI-assisted search visitor may all know different things before they land. We design the page around that starting point.</p></div><div className="rounded-[17px] border border-[#d92f3c]/18 bg-[#190f11]/42 p-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-[#cfc2ae]">The result</p><div className="mt-4 space-y-3">{['Faster understanding','Stronger first-impression trust','Clearer differentiation','Less friction to the next action','A structure that can support new offers and campaigns'].map(item=><div key={item} className="flex items-start gap-2.5 text-[13px] leading-6 text-[#a49598]"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[#d8cbb7]" />{item}</div>)}</div></div></div></section>

      <section className="border-b border-white/[0.055] py-10 sm:py-14"><div className="mx-auto grid w-[min(1080px,calc(100%-28px))] gap-5 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-[#cfc2ae]">Why Booth Marketing</p><h2 className="mt-4 text-[clamp(30px,7vw,44px)] font-semibold tracking-[-0.045em]">We do not start by asking what website you want.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">We start by asking what decision the visitor needs to make, what they need to understand, and what could stop them trusting the business.</p></div><div className="grid gap-2 sm:grid-cols-3">{[['Strategy before design','Understand the buying decision first.'],['Clarity before decoration','Make the offer easy to understand.'],['Conversion before complexity','Every element needs a job.']].map(([title,copy])=><div key={title} className="rounded-[15px] border border-white/[0.07] bg-[#0d0f10] p-4"><p className="text-[13px] font-semibold text-[#e1e1e3]">{title}</p><p className="mt-2 text-[12px] leading-6 text-[#7f8086]">{copy}</p></div>)}</div></div></section>

      <section className="border-b border-white/[0.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto w-[min(900px,calc(100%-28px))] rounded-[18px] border border-[#d92f3c]/18 bg-[#190f11]/42 p-5 sm:p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-[#cfc2ae]">You may not need a rebuild</p><h2 className="mt-3 text-[clamp(28px,6vw,40px)] font-semibold tracking-[-0.04em]">Sometimes the right answer is better messaging, stronger service pages or a clearer conversion path.</h2><p className="mt-3 text-[13px] leading-6 text-[#948a8d]">If the current site should stay, we will tell you. The goal is to improve the decision journey, not sell a rebuild for the sake of it.</p></div></section>

      <section className="py-12 text-center sm:py-16"><div className="mx-auto w-[min(760px,calc(100%-28px))]"><h2 className="text-[clamp(34px,7.5vw,50px)] font-semibold leading-[1.04] tracking-[-0.048em]">Before rebuilding anything, find out what the current site is doing wrong.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">Leave knowing what is hurting trust, what is unclear, where buyers may hesitate and what should change first.</p><Link href="/website-audit" className="mt-6 inline-flex min-h-[50px] items-center justify-center rounded-lg border border-[#efe3cf] bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">Request Website Audit<ArrowRight className="ml-2.5 h-4 w-4" /></Link></div></section>
      <SiteFooter />
    </main>
  )
}
