import Link from 'next/link'
import AdminShell from '@/components/admin/AdminShell'
import { safeLeads, LeadStatus } from '@/lib/leads'

export const dynamic='force-dynamic'
export const revalidate=0

const stages:LeadStatus[]=['NEW','CONTACTED','QUALIFIED','CALL_BOOKED','CLOSED'];const label=(s:string)=>s.replaceAll('_',' ')
export default async function Pipeline(){const {leads,error}=await safeLeads();return <AdminShell section="Pipeline"><div className="mx-auto max-w-[1450px]"><p className="text-[9px] font-bold uppercase tracking-[.22em] text-[#d8cbb7]">Commercial workflow</p><h1 className="mt-3 text-[36px] font-semibold tracking-[-.05em]">Pipeline</h1><p className="mt-2 text-[12px] text-[#707177]">A clear view of where every current enquiry sits.</p>{error&&<p className="mt-5 rounded-xl border border-[#d92f3c]/20 bg-[#190f11] p-4 text-[11px] text-[#d1a3a8]">Pipeline data is temporarily unavailable.</p>}<div className="mt-7 grid gap-3 lg:grid-cols-5">{stages.map(stage=>{const items=leads.filter(l=>l.status===stage);return <section key={stage} className="min-w-0 rounded-[18px] border border-white/[.075] bg-[#0d0f10]"><div className="flex items-center justify-between border-b border-white/[.07] p-4"><h2 className="text-[9px] font-bold uppercase tracking-[.13em] text-[#85868c]">{label(stage)}</h2><span className="rounded-full bg-white/[.04] px-2 py-1 text-[9px] text-[#77787e]">{items.length}</span></div><div className="space-y-2 p-2">{items.map(l=><Link href={`/admin/leads/${l.id}`} key={l.id} className="block rounded-xl border border-white/[.065] bg-[#111315] p-3.5 hover:border-white/[.12]"><p className="truncate text-[11px] font-semibold">{l.company}</p><p className="mt-1 truncate text-[9px] text-[#65666c]">{l.name}</p><div className="mt-3 flex justify-between gap-2 text-[8px] uppercase tracking-[.08em] text-[#55565b]"><span>{l.enquiryType==='AUTOMATION_AUDIT'?'Automation':'Website'}</span><span className="text-[#a99d8a]">{l.opportunityScore||'Unscored'}</span></div></Link>)}{!items.length&&<p className="px-2 py-6 text-center text-[9px] text-[#4f5055]">No leads</p>}</div></section>})}</div></div></AdminShell>}
