import Link from 'next/link'
import AdminShell from '@/components/admin/AdminShell'
import { getLeads } from '@/lib/leads'

const label=(value:string)=>value.replaceAll('_',' ')
export default async function LeadsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
 const params=await searchParams; let leads:Awaited<ReturnType<typeof getLeads>>=[]; let healthy=true; try{leads=await getLeads()}catch{healthy=false}
 const q=(params.q||'').trim().toLowerCase(); const status=params.status||'ALL'
 const filtered=leads.filter(lead=>(!q||[lead.name,lead.email,lead.company,lead.websiteUrl,lead.challenge].some(v=>String(v||'').toLowerCase().includes(q)))&&(status==='ALL'||lead.status===status))
 return <AdminShell section="Leads"><div className="mx-auto max-w-[1280px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.22em] text-[#d8cbb7]">Enquiry workspace</p><h1 className="mt-3 text-[36px] font-semibold tracking-[-0.05em]">Leads</h1><p className="mt-2 text-[12px] text-[#707177]">Search, review and progress every genuine Booth Marketing enquiry.</p></div><span className="rounded-full border border-white/[0.07] px-3 py-2 text-[9px] text-[#696a70]">{leads.length} total</span></div>{!healthy&&<div className="mt-6 rounded-xl border border-[#d92f3c]/20 bg-[#190f11] p-4 text-[11px] text-[#d1a3a8]">Lead data is temporarily unavailable. No records have been fabricated.</div>}
 <form className="mt-7 grid gap-2 rounded-[16px] border border-white/[0.075] bg-[#0d0f10] p-3 sm:grid-cols-[1fr_180px_auto]"><input name="q" defaultValue={params.q} placeholder="Search company, contact, email or website" className="min-h-[46px] rounded-xl border border-white/[0.08] bg-[#090a0b] px-4 text-[12px] outline-none placeholder:text-[#505157] focus:border-[#d8cbb7]/35"/><select name="status" defaultValue={status} className="min-h-[46px] rounded-xl border border-white/[0.08] bg-[#090a0b] px-3 text-[11px] outline-none">{['ALL','NEW','CONTACTED','QUALIFIED','CALL_BOOKED','CLOSED'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select><button className="min-h-[46px] rounded-xl bg-[#efe3cf] px-5 text-[11px] font-semibold text-[#151515]">Apply filters</button></form>
 <section className="mt-4 overflow-hidden rounded-[18px] border border-white/[0.075] bg-[#0d0f10]"><div className="hidden grid-cols-[1.25fr_1fr_.8fr_.65fr_36px] gap-4 border-b border-white/[0.07] px-5 py-3 text-[8px] font-bold uppercase tracking-[0.13em] text-[#55565b] md:grid"><span>Company / contact</span><span>Website</span><span>Status</span><span>Score</span><span/></div>{filtered.length===0?<div className="px-6 py-14 text-center"><p className="text-[14px] font-semibold text-[#a5a6aa]">{leads.length?'No enquiries match these filters.':'No enquiries yet.'}</p><p className="mt-2 text-[10px] leading-5 text-[#55565b]">{leads.length?'Try changing your search or status filter.':'New Website Audit and Automation Audit submissions will appear here automatically.'}</p></div>:<div className="divide-y divide-white/[0.06]">{filtered.map(lead=><Link href={`/admin/leads/${lead.id}`} key={lead.id} className="grid gap-3 p-5 transition hover:bg-white/[0.025] md:grid-cols-[1.25fr_1fr_.8fr_.65fr_36px] md:items-center md:gap-4"><div className="min-w-0"><p className="truncate text-[12px] font-semibold">{lead.company}</p><p className="mt-1 truncate text-[10px] text-[#68696f]">{lead.name} · {lead.email}</p></div><p className="truncate text-[10px] text-[#77787e]">{lead.websiteUrl||'No website supplied'}</p><div><span className="rounded-full border border-white/[0.08] bg-white/[0.02] px-2.5 py-1 text-[8px] uppercase tracking-[0.08em] text-[#8b8c92]">{label(lead.status)}</span></div><p className="text-[10px] text-[#d8cbb7]">{lead.opportunityScore||'Not scored'}</p><span className="text-right text-[#5c5d62]">→</span></Link>)}</div>}</section></div></AdminShell>
}
