CREATE TABLE IF NOT EXISTS leads (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT NOT NULL,
  industry TEXT,
  team_size TEXT,
  challenge TEXT,
  status TEXT NOT NULL DEFAULT 'NEW',
  notes TEXT,
  website_url TEXT,
  opportunity_score TEXT,
  first_impression TEXT,
  trust_issues TEXT,
  conversion_issues TEXT,
  ux_issues TEXT,
  technical_issues TEXT,
  ai_search_issues TEXT,
  recommended_changes TEXT,
  outreach_angle TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
