import { db } from './db'
export type LeadStatus='NEW'|'CONTACTED'|'QUALIFIED'|'CALL_BOOKED'|'CLOSED'
export type Lead={id:string;name:string;email:string;company:string;industry?:string;teamSize?:string;challenge?:string;status:LeadStatus;notes?:string;websiteUrl?:string;opportunityScore?:string;firstImpression?:string;trustIssues?:string;conversionIssues?:string;uxIssues?:string;technicalIssues?:string;aiSearchIssues?:string;recommendedChanges?:string;outreachAngle?:string;createdAt:string;updatedAt?:string}
function map(r:any):Lead{return{id:r.id,name:r.name,email:r.email,company:r.company,industry:r.industry||'',teamSize:r.team_size||'',challenge:r.challenge||'',status:r.status,notes:r.notes||'',websiteUrl:r.website_url||'',opportunityScore:r.opportunity_score||'',firstImpression:r.first_impression||'',trustIssues:r.trust_issues||'',conversionIssues:r.conversion_issues||'',uxIssues:r.ux_issues||'',technicalIssues:r.technical_issues||'',aiSearchIssues:r.ai_search_issues||'',recommendedChanges:r.recommended_changes||'',outreachAngle:r.outreach_angle||'',createdAt:new Date(r.created_at).toISOString(),updatedAt:r.updated_at?new Date(r.updated_at).toISOString():undefined}}
export async function getLeads(){const rows=await db()`SELECT * FROM leads ORDER BY created_at DESC`;return rows.map(map)}
export async function getLeadById(id:string){const rows=await db()`SELECT * FROM leads WHERE id=${id} LIMIT 1`;return rows[0]?map(rows[0]):null}
export async function saveLead(lead:Lead){await db()`INSERT INTO leads(id,name,email,company,industry,team_size,challenge,status,notes,website_url,opportunity_score,first_impression,trust_issues,conversion_issues,ux_issues,technical_issues,ai_search_issues,recommended_changes,outreach_angle,created_at) VALUES(${lead.id},${lead.name},${lead.email},${lead.company},${lead.industry||''},${lead.teamSize||''},${lead.challenge||''},${lead.status},${lead.notes||''},${lead.websiteUrl||''},${lead.opportunityScore||''},${lead.firstImpression||''},${lead.trustIssues||''},${lead.conversionIssues||''},${lead.uxIssues||''},${lead.technicalIssues||''},${lead.aiSearchIssues||''},${lead.recommendedChanges||''},${lead.outreachAngle||''},${lead.createdAt})`;return lead}
export async function updateLead(id:string,u:Partial<Lead>){await db()`UPDATE leads SET status=COALESCE(${u.status??null},status),notes=COALESCE(${u.notes??null},notes),website_url=COALESCE(${u.websiteUrl??null},website_url),opportunity_score=COALESCE(${u.opportunityScore??null},opportunity_score),first_impression=COALESCE(${u.firstImpression??null},first_impression),trust_issues=COALESCE(${u.trustIssues??null},trust_issues),conversion_issues=COALESCE(${u.conversionIssues??null},conversion_issues),ux_issues=COALESCE(${u.uxIssues??null},ux_issues),technical_issues=COALESCE(${u.technicalIssues??null},technical_issues),ai_search_issues=COALESCE(${u.aiSearchIssues??null},ai_search_issues),recommended_changes=COALESCE(${u.recommendedChanges??null},recommended_changes),outreach_angle=COALESCE(${u.outreachAngle??null},outreach_angle),updated_at=CURRENT_TIMESTAMP WHERE id=${id}`}
export async function safeLeads(){try{return{leads:await getLeads(),error:false}}catch{return{leads:[] as Lead[],error:true}}}
